### ISSUE TITLE
What can I do to help 

### ISSUE THREAD

**Issue by 98ahkarhein** [sabo9727/web-design#1]

**Comment by sabo9727** [comment]
I've uploaded sql code on git. You can run and review it and start from there.

**Comment by sabo9727** [comment]
I've also set up project and you can check to-do-list there.

**Comment by 98ahkarhein** [comment]
I've downloaded SQL Code and run on my Mac. Now, I've already started home page and will commit some changes on my branch.  Would you check it?

**Comment by sabo9727** [comment]
I have reviewed your pull request. Let's communicate via email.
